name: Build ImmortalWrt AX6000

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REPO_URL: https://github.com/hanwckf/immortalwrt.git
  REPO_BRANCH: openwrt-25.12
  CONFIG_FILE: .config

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'

      - name: Clone ImmortalWrt source
        run: |
          git clone --depth 1 -b ${{ env.REPO_BRANCH }} ${{ env.REPO_URL }} openwrt
          cd openwrt
          cp ../${{ env.CONFIG_FILE }} .config

      - name: Update feeds & Clean
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make dirclean

      - name: Download toolchain
        run: |
          cd openwrt
          make -j$(nproc) download

      - name: Compile firmware
        run: |
          cd openwrt
          make -j$(nproc)

      - name: Upload firmware artifact
        uses: actions/upload-artifact@main
        with:
          name: ImmortalWrt-AX6000
          path: openwrt/bin/targets/qualcommax/ipq50xx/*.bin
